# Generated by Django 5.1.3 on 2025-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('characteristics', models.CharField(blank=True, max_length=300, null=True, verbose_name='Características')),
                ('id_predio', models.IntegerField(blank=True, null=True, verbose_name='ID Predio')),
                ('id_lote', models.IntegerField(blank=True, null=True, verbose_name='ID Lote')),
            ],
        ),
    ]
